### ISSUE TITLE
Confounding execution

### ISSUE THREAD

**Issue by ursasenior** [Kriosym/JungleTimers#1]
When I compiled and ran this executable it played an irritating piece of music extremely loudly with no further cues to the program's intended purpose or how to stop the noise. Please consider a brief readme in the future.

**Comment by Kriosym** [comment]
There is a readme (wiki) - https://github.com/Kriosym/JungleTimers/wiki/Jungle-Timers-by-Kriosym 
![image](https://cloud.githubusercontent.com/assets/374256/5050097/1e3129c8-6be0-11e4-9319-d5892694a2be.png)
Excerpt....

"You can toggle Background music off by clicking the speaker icon at top-right, this preference is remembered (it won't play again at next launch)."

There's a binary installer that has it built correctly (link is in the wiki).

The UI is extremely intuitive, with a very obvious glowing Speaker icon you can click to disable sound.

I haven't worked on this project in over a year, as I found OverWolf which fills this need.
http://www.overwolf.com/
